### ISSUE TITLE
Review HURUmap as a re-usable Django App

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/HURUmap#1]
### Description

Review HURUmap as a re-usable Django app and create relevant issues / tasks on this issue to fix this.

### Tasks

- [X] Review according to https://docs.djangoproject.com/en/1.11/intro/reusable-apps/
    - [X] Project folder structure
    - [X] Documentation (#29)
    - [X] Tests (#20) 
    - [X] Community
        - [X] CONTRIBUTORS/AUTHORS/**CONTRUBUTING** file
    - [X] Uses the Broadest Requirements Specifiers Possible (since this is a library)
    - [X] README
    - [X] LICENSE
        - [X] Mentioned in the README
        - [X] Separate LICENSE file for easier discover-ability by tools
    - [X] [CHANGELOG](https://keepachangelog.com)
    - [X] `setuptools`
        - [X] setup.py
        - [ ] ~Application information in `hurumap/__init__.py` imported into `setup.py`~
        - [X] MANIFEST.in
            - [X] include README
            - [X] include LICENSE
            - [X] recursive include
                - [X] `hurumap/static *`
                - [X] `hurumap/template *`
                - [X] `docs *`
- [ ] ~v0.1.0 - Package(?) and [create release](https://help.github.com/articles/creating-releases/)~
    - [ ] ~Published on `PyPI`~

**Comment by kilemensi** [comment]
Is there any reason we're sticking with Django v1.9 @DavidLemayian? Wouldn't [v1.11](https://docs.djangoproject.com/en/1.11/intro/reusable-apps/) work just as good?

**Comment by DavidLemayian** [comment]
@kilemensi No reason at all. An upgrade would be awesome! I think the main challenges were censusreporter and wazimap dependencies. cc @phillipahereza @longhotsummer @xybrnet
